### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by c0deing** [k4ds3/mkdocs-exclude-tagged-files#2]
Hi,
when using this plugin i get the following error:

`UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 702: character maps to <undefined>`

The error gets raised in `lib\encodings\cp1252.py, line 23, in decode return codecs.charmap_decode(input,self.errors,decoding_table)[0]`

Im using the mkdocs material theme.

What i did:
1. installed the plugin with: `pip install --upgrade mkdocs-exclude-tagged-files`
2. did the configuration:
```
plugins:
  - mkdocs_exclude_tagged_files:
      tags_to_exclude: ["confidential", "excluded"]
```
3. Put this at the top of a md document:
```
---
tags: ["confidential", "someothertag"]
---
# Content
```

Thanks in advance for your help!

**Comment by JonasDoesThings** [comment]
Hey, could you upload the file in question directly please @c0deing? Looks like some file encoding/decoding issue. 

Doesn't seem too hard to resolve tho, thanks for reporting :)

**Comment by c0deing** [comment]
Hi, yes seems to be some encoding/decoding issue with Latin-1 i think; Did you specify the encoding somewhere where you used an `open()` function? Anyway, which file exactly do you mean? cp1252.py?
See [this](https://stackoverflow.com/questions/9233027/unicodedecodeerror-charmap-codec-cant-decode-byte-x-in-position-y-character)

**Comment by JonasDoesThings** [comment]
Hi sorry for the late reply, had a busy week.

I have now published version 1.0.4, which should fix your issue. Please report back if the issue still exists and other feedback.
Greetings from Austria :)

**Comment by c0deing** [comment]
Hi, I checked it today and it's working. Thank you for fixing!

**Comment by JonasDoesThings** [comment]
Great to hear, awesome :)
